[tool.black]

# ВСІ МОЖЛИВІ НАЛАШТУВАННЯ black

# Відступи
target-version = ['py36', 'py37', 'py38', 'py39', 'py310']  # Список версій Python, для яких застосовуватиметься форматування
include = '\.py$'  # Шаблон файлів, які будуть включені до форматування
exclude = '''
/(
    \.git
  | \.venv
  | _build
  | dist
)/
'''  # Шаблони файлів або директорій, які будуть виключені з форматування

# Розміщення
line-length = 88  # Максимальна довжина рядка; рядки, що перевищують це значення, будуть розбиті
skip-string-normalization = false  # Пропуск нормалізації рядків; використовується для збереження оригінального форматування рядків

# Імпорти
multi-line-output = 3  # Стиль форматування багаторядкових імпортів
combine-as = true  # Об'єднувати кілька вказівок `as` в одну
combine-star = true  # Об'єднувати кілька вказівок `import *` в одну

# Вирази та операції
string-normalization = true  # Нормалізація рядків; заміна одиночних та подвійних лапок на потрібний тип
force-string-normalization = false  # Примусова нормалізація рядків, навіть якщо вони не змінюються
pyi-union = false  # Форматувати типи з `Union` в стиль `X | Y` замість `Union[X, Y]`
enum-comma = true  # Додавати кому після останнього елементу в енумах
experimental-string-processing = false  # Експериментальна обробка рядків; приховування відмінностей між одинарними та подвійними лапками
experimental-allow-single-quotes = false  # Дозволяти використання одинарних лапок для рядків
experimental-string-quotes = false  # Експериментальні лапки рядків; використання одинарних лапок там, де це можливо

# Форматування коментарів
comment-prefix = '# '  # Префікс коментарів
inline-comment-expression = '# '  # Роздільник для коментарів у тому ж рядку
python-disambiguate = false  # Використовувати додаткові пробіли для розрізнення між Python-кодом та коментарями
