# Вказуємо базовий образ Python 3.12, на основі якого створимо новий образ
FROM python:3.12

# Копіюємо файл exposed_command.py з локальної файлової системи (зліва) до контейнера,
# який буде створено. Шлях /other_folder/exposed_command.py вказує, куди саме в контейнері хочемо скопіювати
COPY exposed_command.py /other_folder/exposed_command.py

# Встановлюємо Flask у контейнері
RUN pip install flask

# Вказуємо команду, яка буде виконуватись при запуску контейнера, створеного з образу.
# В даному випадку команда python3 вказує на виконання інтерпретатора Python версії 3,
# а /other_folder/exposed_command.py вказує шлях до файлу в середині контейнера.
CMD ["python3", "/other_folder/exposed_command.py"]

# Вказуємо, що контейнер відкриває порт 8080 для зовнішніх з'єднань
EXPOSE 8080