# Вказуємо базовий образ python 3.12 на основі якого створимо новий образ
FROM python:3.12

# Вказуємо автора, його електронну пошту, версію образу, опис тощо
LABEL maintainer="Vadym Korolov <vadkor@ukr.net>"
LABEL version="1.0"
LABEL description="This is a sample Docker image with labal command."
LABEL org="None"
LABEL url="https://example.com/my-project"

# Копіюємо файл volume_command.py з локальної файлової системи (зліва) до контейнера,
# який буде створено. Шлях /env_command.py вказує, куди саме в контейнері хочемо скопіювати
COPY using_label.py /using_label.py

# Встановлюємо змінну середовища MY_ENV_VAR зі значенням "Hello, Docker!"
ENV MY_ENV_VAR="Hello, Docker!"

# Команда VOLUME вказує, що /data в контейнері є монтуємим томом
VOLUME /data

# Вказуємо команду, яка буде виконуватись при запуску контейнера створеного з образу.
# В даному випадку команда python3 вказує на виконання інтерпретатора Python версії 3,
# а /volume_command.py вказує шлях до файлу в середині контейнера.
CMD ["python3", "/using_label.py"]